name: HikeSEO | PHP linting

on:
  pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  hikeseo-php-lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          extensions: gd
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSER_GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: PHP CS Fixer cache
        uses: actions/cache@v3
        with:
          path: tmp/.php-cs-fixer.cache
          key: phpcsfixer-cache-${{ github.sha }}
          restore-keys: |
            phpcsfixer-cache-

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test -vvv --config ./pint.json
